/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro_func;

import entities.Busca;
import entities.Chefe;
import entities.Subordinado;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author Wendel Muniz
 */
public class tela_cadastro extends javax.swing.JFrame {

    public static String nomeFunc;
    public static String cargoHabilitacao;
    public static String funcao;
    public static String nomeChefe;
    public static String TodosChefes;
    public static List<Chefe> listaChefe = new ArrayList<>();
    public static List<Subordinado> listaSubordinado = new ArrayList<>();

    
    public static boolean verificar(String nomeFunc){

        return nomeFunc.matches("^[a-zA-Z]+$");
          
    }
    
    public tela_cadastro() {
        initComponents();
        
        jChefeIme.removeAllItems();
        jHabilitacao.removeAllItems();
        jRbuscar.removeAllItems();
        jRnome.removeAllItems();
        
        jChefeIme.addItem("Jener de Souza Novais");
        jRnome.addItem("Jener de Souza Novais");
        jHabilitacao.addItem("Chefe");
        jHabilitacao.addItem("Subordinado");
        jRbuscar.addItem("Chefe");
        jRbuscar.addItem("Subordinado");
        butoes.add(jTecAdm);
        butoes.add(jProf);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butoes = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jChefeIme = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNomeFunc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTecAdm = new javax.swing.JRadioButton();
        jProf = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jHabilitacao = new javax.swing.JComboBox<>();
        jCadastrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRbuscar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jRnome = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBuscados = new javax.swing.JTextArea();
        jLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/images/753210.png")).getImage());

        jChefeIme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jener de Souza Novais", "Item 2", "Item 3", "Item 4" }));
        jChefeIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChefeImeActionPerformed(evt);
            }
        });

        jLabel1.setText("CHEFE IMEDIATO:");

        jLabel2.setText("NOME DO FUNCIONÁRIO:");

        jNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeFuncActionPerformed(evt);
            }
        });

        jLabel3.setText("FUNÇÃO:");

        jTecAdm.setText("TÉCNICO ADMINISTRATIVO");
        jTecAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTecAdmActionPerformed(evt);
            }
        });

        jProf.setText("PROFESSOR");
        jProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProfActionPerformed(evt);
            }
        });

        jLabel4.setText("HABILITAÇÃO:");

        jHabilitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jHabilitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHabilitacaoActionPerformed(evt);
            }
        });

        jCadastrar.setText("CADASTRAR");
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNomeFunc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChefeIme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTecAdm)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jHabilitacao, 0, 346, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCadastrar))))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChefeIme))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTecAdm)
                    .addComponent(jProf))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCadastrar))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ENTRADA FUNCIONÁRIO PÚBLICO", jPanel1);

        jLabel5.setText("BUSCAR:");

        jRbuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("NOME FUNCIONÁRIO PÚBLICO:");

        jRnome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jRnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRnomeActionPerformed(evt);
            }
        });

        jLabel7.setText("VISUALIZAÇÃO DOS RESULTADOS:");

        jBuscar.setText("CONSULTAR");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jBuscados.setBackground(new java.awt.Color(242, 242, 242));
        jBuscados.setColumns(20);
        jBuscados.setRows(5);
        jScrollPane1.setViewportView(jBuscados);

        jLimpar.setText("LIMPAR");
        jLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbuscar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRnome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jBuscar)
                    .addComponent(jLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("RELÁTORIOS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChefeImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChefeImeActionPerformed

    }//GEN-LAST:event_jChefeImeActionPerformed

    private void jNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeFuncActionPerformed

    private void jTecAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTecAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTecAdmActionPerformed

    private void jProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProfActionPerformed

    private void jHabilitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHabilitacaoActionPerformed

    }//GEN-LAST:event_jHabilitacaoActionPerformed

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed

        if(jTecAdm.isSelected()==true || jProf.isSelected()==true){
            nomeFunc = jNomeFunc.getText();




            if(verificar(nomeFunc)==true){


                nomeChefe = (String) jChefeIme.getSelectedItem();
                
                jNomeFunc.setText(null);
                cargoHabilitacao = (String) jHabilitacao.getSelectedItem();
                if(jTecAdm.isSelected()){   
                    funcao = "Tecnico Administrativo";   
                }
                else if(jProf.isSelected()){
                    funcao = "Professor"; 
                }
                if(cargoHabilitacao.equals("Subordinado")){

                    jRnome.addItem(nomeFunc);
                    Subordinado s = new Subordinado(nomeChefe, nomeFunc, funcao);
                    s.setFuncao(funcao);
                    s.setNome(nomeFunc);
                    s.setIdChefe(nomeChefe);
                    listaSubordinado.add(s);

                }else if(cargoHabilitacao.equals("Chefe")){

                    jChefeIme.addItem(nomeFunc);
                    jRnome.addItem(nomeFunc);
                    Chefe c = new Chefe(nomeChefe, nomeFunc, funcao);
                    c.setFuncao(funcao);
                    c.setNome(nomeFunc);
                    c.setIdSubordinado(nomeChefe);
                        
                    listaChefe.add(c);          
                }
            }else{ 
                JOptionPane.showMessageDialog(null,"Palavra invalida!");
                jNomeFunc.setText(null);
            }
        }else{
            if (jCadastrar.isSelected()){
                JOptionPane.showMessageDialog(null, "Nenhuma função selecionanda!");
                jNomeFunc.setText(null);
            }
        }
    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jRnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRnomeActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        
        Busca b = new Busca();
        b.buscar(jRbuscar, jRnome, jBuscados, jChefeIme);

    }//GEN-LAST:event_jBuscarActionPerformed

    private void jLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparActionPerformed
        jBuscados.setText(null);
    }//GEN-LAST:event_jLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup butoes;
    private javax.swing.JTextArea jBuscados;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JComboBox<String> jChefeIme;
    private javax.swing.JComboBox<String> jHabilitacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLimpar;
    private javax.swing.JTextField jNomeFunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jProf;
    private javax.swing.JComboBox<String> jRbuscar;
    private javax.swing.JComboBox<String> jRnome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jTecAdm;
    // End of variables declaration//GEN-END:variables
}
